### PR TITLE
MRG: Graphics module updates

### PR DESCRIPTION
**Pull request by kellieotto**

### CODE REVIEW

**Comment by paciorek** [comment]
Looks nice!  No particular suggestions. I'll probably make some minor edits
once it's merged into my master.

I think it's fine to leave the breakout problems as is, having them make
plots on the airline data, but if you have any good ideas for different or
modified problems that you think would be better practice / illustration of
the ideas, feel free.

It's probably rather more than you can cover in detail in the 45-50 minutes
I'm trying to keep to for the demo/presentation part of each module, so
would be great if you think through in advance what you want to focus on
and what to skim through quickly.

**Comment by kellieotto** [comment]
I made some minor changes and rebased.  Should be good to merge.

**Comment by paciorek** [comment]
So the 'country' column in the medals data file has a bunch of NAs. Not sure if an issue in the data processing workflow or if one should be using NOC field instead. But if you could take a look and modify to avoid this, that would be good.

Also the bar plots section is getting errors (possibly because of NAs from the afore-mentioned). 

When you make modifications, please first pick up the commits I've made in berkeley-scf/r-bootcamp-2016 as I did some editing for line spacing in module8_graphics.Rmd.

I'm going to send out info to participants today including a link to the repo, but no worries if this doesn't get fixed immediately.

**Comment by kellieotto** [comment]
Oh interesting. I was hasty and didn't check closely. All the NA countries are ones that no longer exist. I'll switch to country codes instead.

**Pull request merged**
