### PR TITLE
Module 5

### PR DESCRIPTION
**Pull request by rochelleterman**
- replaced plyr/reshape2 with dplyr/tidyr. 
- changed the example dataset from tips / airplanes to country-year data ('gapminder')
- revised the prose
- added new challenges
- knitted to HTML, although I couldn't figure out how to make the slides...

### CODE REVIEW

**Comment by paciorek** [comment]
Super, I'll take a look. Thanks!

For future reference, if you have make on your machine, "make 5" should
create the slides as well as the single-page html.

**Comment by paciorek** [comment]
Hi Rochelle,

Some thoughts:

0) This is great - exactly what I had in mind, it's a nice dataset, and I
like how you illustrate everything.

1) I did a bit of R syntax manipulation to put it in the style used in
other modules. In part I try to reinforce certain stylistic stuff (putting
spaces after commas and what-not) in hopes that participants will use that
style. My changes to your content are in the original
berkeley-scf/r-bootcamp-2016, so make sure to pick those up before doing
further edits on your end.

2) In slide 10 (perhaps just verbally) you might mention that Module 4 gave
ways to do some of the split-apply-combine type stuff, but that the
approach here is even cleaner than that (and even more so better than the
manual code you show).

3) (minor comment - take or leave) in slide 11, when I look at the str()
result or just directly look at "gapminder %>% group_by(continent)" it
doesn't really look like a list. And the dimensions still look like the
original data frame. So I thought this might be a bit confusing. I wonder
if there is some other way to describe the grouped_df?

4) Your preference in terms of your presentation style, but for the most
part I show the output of the R code chunks in the HTML in the other
modules. But if you prefer it as it is now with just the code, that's fine
by me.

5) To motivate slide 19, it might help to see `head(gap_long)`. (Actually
you might look over the other slides and see if using `head()` in addition
to or instead of `str()` might be useful.  I think for newcomers (actually
for me too) see a few rows as examples is very helpful.

6) (minor comment - take or leave) would it be more in the spirit of the
module to have the `as.integer` operation be done through another dplyr
action with `mutate` (not sure if mutate will change a column in place...)

7) gap_long is not the same as the original gapminder dataset in that it
doesn't have separate columns for gdp, lifeExp, and pop. So while I think
the long format is useful, particularly in certain circumstances, the
original gapminder format makes the most sense in many situations. So I'd
be careful about calling the long form 'correct'.  Would Hadley really
define the canonical long format to _not_ have separate columns for gdp,
pop, lifeExp?  Or would it make sense to create a "long-ish" format that
has separate columns for gdp, pop, lifeExp in your demo?  I'm not sure what
the best thing to do is in terms of illustrating dplyr, but wanted to raise
my own personal confusion on this point.

8) in slide 20, 'gap_wide' never takes the same form as the truly wide
dataset, so I think it's confusing to name it 'gap_wide'. Rather, you are
taking the long format and turning it into the somewhat less long/somewhat
more wide format, but not into the full wide format.

9) I'll plan to move the breakout solutions into "solutions/solutions.Rmd"
once things are settled (or if you're up for it, please do).

10) breakout problem #2 doesn't quite work because it doesn't deal with the
fact that year is also in the dataset, so it seems to compute the total pop
of a continent summed over all years. I think that will be confusing to
people in terms of interpreting what the output is.

11) Can you make the solution to #6 use dplyr grammar to create 'sign'?

12) is there a way to force more rows to be printed out from a tbl_df?
E.g., occasionally I might want to do
gapminder[1:100, ]
but it suppresses the printout. Might be nice to show quickly if there is
an easy way.

13) Regressing on country in problem 6 is problematic in that all the
p-values are very near zero. I didn't take the time to sort out exactly
what is playing out, but many countries are either all 0s or all 1s for all
of their years of data, so that may be part of it. So I'd suggest you stick
with other covariates.

**Comment by rochelleterman** [comment]
Great -- Thanks for your quick notes, Chris. I'll make those edits and get back to you shortly.

**Comment by paciorek** [comment]
Thanks. No particular hurry - if you can get to it by end of the week my
plan is to share all modules with the attendees as of next Monday or so.

**Pull request merged**
